name: Update TVBox Config

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23,9 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requests
        run: pip install requests

      - name: Fetch and update config
        run: |
          python << 'EOF'
          import requests, json, os
          from datetime import datetime

          url = "http://cdn.qiaoji8.com/tvbox.json"
          output = "西充影视.json"

          new_live = {
            "name": "西瓜直播",
            "type": 3,
            "url": "https://raw.githubusercontent.com/xichongguo/live-stream/refs/heads/main/live/current.m3u8",
            "epg": "https://epg.zbds.top/",
            "logo": "",
            "categories": "体育,电影,综艺"
          }

          try:
            res = requests.get(url, headers={'User-Agent': 'TVBox-Updater'}, timeout=10)
            data = res.json()
          except Exception as e:
            print(f"❌ Fail: {e}")
            exit(1)

          if 'lives' not in data:
            data['lives'] = []

          if not any(l.get('url') == new_live['url'] for l in data['lives']):
            data['lives'].append(new_live)
            print("✅ Live added")

          for live in data.get('lives', []):
            if 'epg' in live:
              live['epg'] = "https://epg.zbds.top/"

          if 'sites' in data and data['sites']:
            data['sites'][0]['name'] = "西充影视"

          try:
            with open(output, 'w', encoding='utf-8') as f:
              json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"✅ Saved: {output}")
          except Exception as e:
            print(f"❌ Save failed: {e}")
          EOF

      - name: Commit file
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add 西充影视.json
          git diff --quiet && git diff --cached --quiet || git commit -m "auto: update config $(date)"
          git push
